server:
  port: 8001
mybatis:
  type-aliases-package: com.buba.pojo
spring:
  application:
    name: microservicecloud-dept
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

    dbcp2:
      min-idle: 5  # 数据库连接池的最小维持连接数
      initial-size: 5  # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance: #服务名称的修改
    instance-id: microservicecloud-dept-hystrix
    prefer-ip-address: true     #访问路径可以显示IP地址

info: #该服务的描述
  app.name: buba-microservicecloud
  company.name: www.buba.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$



#hystrix:
    # command:
    #   default:
    #     execution:
    #      isolation:
    #       thread:
  #         timeoutInMilliseconds: 3000 # 设置hystrix的超时时间,默认为1000ms