server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

#springcloud网关配置
zuul:
  prefix: /api #可以设置统一的公共前缀
  ignored-services: "*" #原真实服务名忽略，忽略全部用“*”,忽略一个用服务名
  routes: #路由
    mydept:   #面向服务的路由配置,此名称可以自定义
      serviceId: microservicecloud-dept  #服务名
      path: /mydept/**  #映射的url



info:
  app.name: microcloud-gateway
  company.name: www.buba.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$